spring.application.name=IT-Help-Desk

# Persistent H2 database
spring.datasource.url=jdbc:h2:file:./data/helpdesk
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Keep database tables and data between restarts
spring.jpa.hibernate.ddl-auto=update